services:
  babystep:
    image: ghcr.io/regalen/babystep:latest
    container_name: babystep
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/babystep/config:/config
    ports:
      - 3000:3000
    restart: unless-stopped
